### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by IvanUkhov** [cmr/openblas-provider#1]
Hi,

I’m wondering if `blas` in the middle is really needed. `openblas-provider` and `netlib-provider` sound good. Besides, apart from BLAS, they provide LAPACK as well.

Regards,
Ivan

**Comment by IvanUkhov** [comment]
@cmr, what do you think? If you rename the repositories, I can do the rest.

**Comment by cmr** [comment]
@IvanUkhov I've renamed the repositories.

**Comment by cmr** [comment]
Renamed openblas-provider and publishing...

**Comment by cmr** [comment]
Renamed netlib-provider and publishing...

**Comment by cmr** [comment]
Done.

**Comment by IvanUkhov** [comment]
Awesome! Thanks! I will polish READMEs and get rid of some leftovers.
