### ISSUE TITLE
Specifying OpenBLAS directory

### ISSUE THREAD

**Issue by gustavla** [cmr/openblas-provider#4]
I have an OpenBLAS installation in a folder that the installation is not finding. I have solved this locally by adding the following lines in `build.rs` to `use_system`:

    if let Ok(v) = var("CARGO_FEATURE_OPENBLAS_DIR") {
        println!("cargo:rustc-libdir={}", v);
        println!("cargo:rustc-link-search=native={}", v);
    }

I was wondering if there is another solution that doesn't require a custom modification, or would something like this make an appropriate PR?

**Comment by IvanUkhov** [comment]
Currently it is not straightforward to detect whether OpenBLAS is installed as OpenBLAS [doesn’t provide](https://github.com/xianyi/OpenBLAS/issues/598) pkg-config files out of the box; although, some Linux distributions do it on their own. So we cannot take advantage of the [pkg-config](https://crates.io/crates/pkg-config) crate, which would be ideal.

The `system-openblas` feature is a partial workaround: it tells the compiler that it should try to link to a library called `openblas`; however, it doesn’t tell where the library is. The library is assumed to be in one of the standard paths, and the linker should be able to find it on its own. Apparently it doesn’t work for you. I’ll look into this, but for now what you could do is to create a symlink to your `libopenblas.dylib` or `libopenblas.so` in one of the `-L` directories that the linker is aware of. One such directory is always the folder with Rust libraries. In my case, it is `$RUST_ROOT/lib/rustlib/x86_64-apple-darwin/lib`; you could create a symlink there.

@cmr, any thoughts?


Regards,
Ivan

**Comment by gustavla** [comment]
Adding the path to `LIBRARY_PATH` worked for me, so I'm closing this. Thanks!
