### ISSUE TITLE
Crate features need to be positive

### ISSUE THREAD

**Issue by bluss** [cmr/openblas-provider#8]
Cargo unions crate features automatically, so `exclude-cblas` would need to be turned into a default `include-cblas` to work with that scheme.

**Comment by IvanUkhov** [comment]
@bluss, is it some kind of new policy or guideline? Where can I read more about it? Thanks.

**Comment by bluss** [comment]
it's in the design and mechanics of feature flags. The docs doesn't really spell it out though. http://doc.crates.io/manifest.html#the-features-section

**Comment by IvanUkhov** [comment]
Done. Thanks!

**Comment by bluss** [comment]
Thank you!

**Comment by bluss** [comment]
I think it's a sign that the provider setup will eventually clash with cargo's feature flag semantics unfortunately. Don't think there is a supported way to handle it.
